### PR TITLE
Task 02

### PR DESCRIPTION
**Pull request by jorgemgn**
Hello,

**PR description**
This PR solves issue [Task-02: Variable types](https://github.com/jorgemgn/curso-cplus-cplus/issues/6) where I have learned how to use the basic types of C++.

**Sample output**

```sh
$ a 
$ b 
$ 31 
$ 15.5 
$ B 
$ 10 
```
**How to use**
```sh
$ cd src/task-02
$ g++ main.cc -o main
$ ./main.o
```
Greetings, Jorge

### CODE REVIEW

**Comment by jesusgn90** [comment]
## About the PR itself
Replace the title `task-02-1 completed` with `Task 02`

Give it a better structure, for example:

**Description**
This PR solves https://github.com/jorgemgn/curso-cplus-cplus/issues/6, where I've learned how to use the basic types of C++.

**Sample output**

```sh
$ ./main
a 
b 
31 
15.5 
B 
10 
```

**How to use**

```sh
$ cd src/task-02
$ g++ main.cc -o main
$ ./main
```

## About the code

I'm going to explain and to fix every part of your code you can easily learn about the corrections for the next time.

**Imports**

Please do not mix C and C++ libraries:

```c
#include <iostream>
#include <stdio.h>
```

As I said, the `stdio.h` is for C, and `iostream` is the _equivalent_ for C++. Just use the proper library:

```c
#include <iostream>
```

**Print two characters, "a" and "b"**

Your code:

```c
//Print two characters. "a" and "b".

    char leter1 = 'a'; //Valor para la letra 1
    char leter2 = 'b'; //Valor para la letra 2

        cout << leter1 << endl; //Muestra en pantalla el valor de la letra 1
        cout << leter2 << endl; //Muestra en pantalla el valor de la letra 2
```

The format is wrong. The comments are useless.

My suggestion:

```c
// Print two characters, "a" and "b".
char char_a = 'a'; 
char char_b = 'b'; 
cout << char_a << endl;
cout << char_b << endl; 
```
**Add two integers and print the result. Result should be an integer**

Your code:

```c
//Add two integers and print the result. Result should be an integer.

    int num1 = 11; //Valor para el número 1
    int num2 = 20; //Valor para el número 2

        cout << num1 + num2 << endl; //Muestra en pantalla el resultado de la suma de los do números
```

The format is wrong. The comments are useless. You should not do operations inside `cout` blocks, instead, use a new variable.

My suggestion:

```c
// Add two integers and print the result. The result should be an integer.
int num1 = 11; 
int num2 = 20; 
int sum = num1 + num2;
cout << sum << endl; 
```

**Using those two integers, calculate the average and print it. The result should use decimals**

Your code:

```c
//Using those two integers, calculate the average and print it. The result should use decimals.

    float num_1 = 11; //Usamos un tipo no entero, flotante, que permite cifras decimales, para el número 1
    float num_2 = 20; //Usamos un tipo no entero, flotante, que permite cifras decimales, para el número 2

    float average = ((num_1 + num_2) / 2); //Media aritmética de los dos

        cout << average << endl; //Muestra en pantalla el resultado de la media aritmética
```

The format is wrong. The comments are useless. And this time there are more issues to take care of. You must not create two new variables (`num_1` and `num_2`). Instead, you should store the result into a float variable but using the first two integers (`num1` and `num2`) as the task says.

My suggestion:

```c
// Using those two integers, calculate the average and print it. The result should use decimals.
float average = (float) (num1 + num2) / 2; 
cout << average << endl; 
```

A different suggestion:

```c
// Using those two integers, calculate the average and print it. The result should use decimals.
float average = (num1 + num2) / 2.0; 
cout << average << endl; 
```

The explanation is pretty simple:

- If you add two integers (`num1` and `num2`) and then you divide the result by an integer, you are obtaining an integer (15 instead of 15.5). The trick here is to force the result to be a float using a [casting](http://c.conclase.net/curso/?cap=042) (solution number one) or using a float like a number, for example, 2.0 instead of just 2 (solution number two).

**Using the same integers. If the first integer is greater than the second integer, print "A", otherwise print "B"**

Your code:

```c
//Using same integers. If the first integer is greater than the second integer, print "A", otherwise print "B".

    bool mayor = num1 > num2; //Uso una variable de tipo booleano, permite dos valores exclusivamente, true o false

    if (mayor) //True
        {
            cout << "A" << endl; //Si es true, muestra en pantalla A
    }
    else //False
        {
            cout << "B" << endl; //Si el false, muestra en pantalla B
    }
```
The format is wrong. The comments are useless. Also, there is a simpler solution for this.

My suggestion:

```c
// Using same integers. If the first integer is greater than the second integer, print "A", otherwise print "B".
bool mayor = num1 > num2; 
if (mayor) 
{
    cout << "A" << endl; 
}
else
{
    cout << "B" << endl; 
}
```

My second suggestion:

```c
bool mayor = num1 > num2; 
cout << (mayor ? "A" : "B") << endl;
```
**Create a simple enum with three elements, then print one of its elements**

Your code:

```c
//Create a simple enum with three elements, then print one of its elements.

    enum fruits {coco = 10, banana = 1, lemon};  //Lista de elementos, con distintos valores asociados a cada elemento
    
    fruits notyellow = coco; //Variable de tipo fruits le asocio el valor coco a mi variable

            cout << notyellow << endl; //Muestro en pantalla el valor de esa variable, que corresponde al valor númerico de coco, 10
```

The format is wrong. The comments are useless. Also, I expect to see a more advanced usage of the enum here but it's okay so far, further exercises will challenge you about the enum type.

My suggestion:

```c
// Create a simple enum with three elements, then print one of its elements.
enum fruits {coco = 10, banana = 1, lemon};  
fruits notyellow = coco; 
cout << notyellow << endl; 
```

## Misc, things also wrong that you should learn

The generated binary must be called main or whatever you want but not ending with ".o" that's a reserved extension for objects. Instead of `g++ main.cc -o main.o` it should be `g++ main.cc -o main`. 

Files ending with `.o` are special files and in C++ are objects (files a step before being a binary but they are not "code"). 

> Each C++ source file needs to be compiled into an object file. The object files resulting from the compilation of multiple source files are then linked into an executable, a shared library, or a static library (the last of these being just an archive of object files). C++ source files generally have the .cpp, .cxx or .cc extension suffixes.

_From https://www.toptal.com/c-plus-plus/c-plus-plus-understanding-compilation_

You removed the `.gitignore` file (https://github.com/jorgemgn/curso-cplus-cplus/pull/7/files#diff-a084b794bc0759e7a6b77810e01874f2), why???

You've included binary and object files:

- https://github.com/jorgemgn/curso-cplus-cplus/pull/7/files#diff-2f1e9d6fd10a8ae991fd52cd9c7cb98b
- https://github.com/jorgemgn/curso-cplus-cplus/pull/7/files#diff-0060943a11e8ef0169c6ef8203a9a209
- https://github.com/jorgemgn/curso-cplus-cplus/pull/7/files#diff-c545e9b1c5a048dd990881d59cc7d1f8

Those files should be ignored in the `.gitignore` you removed...

Multiline comments should use `*` on every line:

Wrong:

```c
/**
asd
asd
 */
```

Good:

```c
/**
 * asd
 * asd
 */
```


Regards!

**Comment by jorgemgn** [comment]
Hello,
First of all, thank you for the review and advices on https://github.com/jorgemgn/curso-cplus-cplus/issues/6, I have already fixed the errors [here](https://github.com/jorgemgn/curso-cplus-cplus/pull/7/files).
To finish my comment, tell that the creation of the Git Ignore file is still pending and I will do it when I can. 
Good night

**Comment by jesusgn90** [comment]
image

Once again, the code was not tested either compiled, please test things before uploading them, thanks.

**Comment by jesusgn90** [comment]
image

The description is still wrong.

**Comment by jesusgn90** [comment]
Hi @jorgemgn ,

I cleaned/manipulated the commit history:

image


I've also fixed the bug on the `float` line, now it's working. Previously you had this:

```c
float average = (float) (num_1 + num_2) / 2);
```

The problem was that `num_1` and `num_2` were not declared and `2);` was wrong, it had an extra `)` breaking the code. Now it's fixed:

```c
float average = (float) (num1 + num2) / 2;
```

On the other hand, I've also fixed the `.gitignore` and the `Makefile` files. Now and onwards binary files, object files and exe files will be ignored. Regarding of the Makefile, please use this next time:

For the `Makefile` you don't need to go to under src/task-N, you can stay out of src/, that's in the root of the project (/).

Compile task-N:

```sh
$ make task-N
```

Example:

```c
$ make task-02
```

Compile all tasks:

```sh
$ make all
```

Clean (remove) generated binary and object files:

```
$ make clean
```

**Pull request merged**
